In [49]:
from squlearn.observables import *


In [65]:
observable

SparsePauliOp(['Z'],
              coeffs=[1.+0.j])

In [66]:
SummedPaulis(num_qubits)

SparsePauliOp(['I', 'Z'],
              coeffs=[ParameterExpression(1.0*p[0]), ParameterExpression(1.0*p[1])])

In [72]:
from squlearn.observables import *
from squlearn.encoding_circuit import QiskitEncodingCircuit, LayeredEncodingCircuit
import numpy as np
from squlearn.qnn.lowlevel_qnn import LowLevelQNN
from squlearn import Executor


num_qubits = 1
param_ini = []



x_array = np.array([[1], 
                    [1], 
                    [2], 
                    [2]])

circuit = LayeredEncodingCircuit(num_qubits, 1, "x")
circuit.Rz("x") 

In [82]:
observable = SummedPaulis(num_qubits)
observable = SinglePauli(1, op_str="Z", parameterized=True)
param_obs = [(1) for i in range(observable.num_parameters)] # real coefficients

qnn_pennylane = LowLevelQNN(circuit, observable, Executor("pennylane"))
qnn_qiskit = LowLevelQNN(circuit, observable, Executor("qiskit"))

print("Evaluating fnuction with qiskit and pennylane with complex coefficients for the observable")
print(qnn_qiskit.evaluate(x_array, [], param_obs, "f")["f"])
print(qnn_pennylane.evaluate(x_array, [], param_obs, "f")["f"])

print("Evaluating derivatives with qiskit and pennylane with complex coefficients for the observable")
print(qnn_qiskit.evaluate(x_array, [], param_obs, "dfdx")["dfdx"])
print(qnn_pennylane.evaluate(x_array, [], param_obs, "dfdx")["dfdx"])

Evaluating fnuction with qiskit and pennylane with complex coefficients for the observable
[1. 1. 1. 1.]
[1. 1. 1. 1.]
Evaluating derivatives with qiskit and pennylane with complex coefficients for the observable
[[0.]
 [0.]
 [0.]
 [0.]]
[[0]
 [0]
 [0]
 [0]]


In [81]:
observable = SinglePauli(1, op_str="Z", parameterized=False) # non-parameterized observable does not give an error
param_obs = [(1 + 0j) for i in range(observable.num_parameters)] # complex coefficients
qnn_pennylane = LowLevelQNN(circuit, observable, Executor("pennylane"))
qnn_qiskit = LowLevelQNN(circuit, observable, Executor("qiskit"))


print("Evaluating fnuction with qiskit and pennylane with complex coefficients for the observable")
print(qnn_qiskit.evaluate(x_array, [], param_obs, "f")["f"])
print(qnn_pennylane.evaluate(x_array, [], param_obs, "f")["f"])

print("Evaluating derivatives with qiskit and pennylane with complex coefficients for the observable")
print(qnn_qiskit.evaluate(x_array, [], param_obs, "dfdx")["dfdx"])
print(qnn_pennylane.evaluate(x_array, [], param_obs, "dfdx")["dfdx"])

Evaluating fnuction with qiskit and pennylane with complex coefficients for the observable
[1. 1. 1. 1.]
[1. 1. 1. 1.]
Evaluating derivatives with qiskit and pennylane with complex coefficients for the observable
[[0.]
 [0.]
 [0.]
 [0.]]
[[0]
 [0]
 [0]
 [0]]


In [83]:
observable = SinglePauli(1, op_str="Z", parameterized=True) # parameterized observable does not give an error
param_obs = [(1 + 0j) for i in range(observable.num_parameters)] # complex coefficients
qnn_pennylane = LowLevelQNN(circuit, observable, Executor("pennylane"))
qnn_qiskit = LowLevelQNN(circuit, observable, Executor("qiskit"))


print("Evaluating fnuction with qiskit and pennylane with complex coefficients for the observable")
print(qnn_qiskit.evaluate(x_array, [], param_obs, "f")["f"])
print(qnn_pennylane.evaluate(x_array, [], param_obs, "f")["f"])

print("Evaluating derivatives with qiskit and pennylane with complex coefficients for the observable")
print(qnn_qiskit.evaluate(x_array, [], param_obs, "dfdx")["dfdx"])
print(qnn_pennylane.evaluate(x_array, [], param_obs, "dfdx")["dfdx"])

Evaluating fnuction with qiskit and pennylane with complex coefficients for the observable
[1. 1. 1. 1.]
[1. 1. 1. 1.]
Evaluating derivatives with qiskit and pennylane with complex coefficients for the observable
[[0.]
 [0.]
 [0.]
 [0.]]


ValueError: cannot reshape array of size 32 into shape (4,1,4)